name: run_r_script_kumu

# Controls when the workflow will run
on:
  schedule:
    - cron: "20 08 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GSHEET_ACCESS_PASSWORD: ${{ secrets.GSHEET_ACCESS_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 1
          
      - name: Run-r-script
        run: | 
          Rscript -e "source('scripts/2a_data_for_kumu.R')"

