name: run_r_script_kumu

# Controls when the workflow will run
on:
  schedule:
    - cron: '11 12 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GSHEET_ACCESS_PASSWORD: ${{ secrets.GSHEET_ACCESS_PASSWORD }}
      R_KEEP_PKG_SOURCE: yes
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          
      - name: Manually install libsodium
        run: 'sudo apt-get install -y libsodium-dev'

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 1
          
      - name: Run-r-script
        run: 
          Rscript -e "source('scripts/2a_data_for_kumu.R')"

